### numpy의 내장함수

In [1]:
import numpy as np

In [5]:
# 평균 구하기
np.mean(range(1,10))

5.0

In [7]:
# 합계 구하기
np.sum(range(1,1001))

500500

In [8]:
# 분산구하기
np.var(range(1,11))

8.25

In [9]:
# 표준편차
np.std(range(1,101))

28.86607004772212

In [10]:
import math

In [28]:
# 표준편차가 분산의 제곱근 인걸 증명하기
print(math.sqrt(np.var(range(1,11))) == np.std(range(1,11)))

print(np.std(range(1,11))**2 == np.var(range(1,11) ))

True
True


In [47]:
print(type(math.sqrt(np.var(range(1,11)))))
print(type(np.std(range(1,11))))

<class 'float'>
<class 'numpy.float64'>


In [31]:
print(np.max(range(1,11)))
print(np.min(range(1,11)))

10
1


In [32]:
np.median(range(1,11)) # 중앙값

5.5

In [39]:
# 누적합 보기
print(np.cumsum(range(1,11)))
print(type(np.cumsum(range(1,11))))

[ 1  3  6 10 15 21 28 36 45 55]
<class 'numpy.ndarray'>


In [41]:
np.cumsum(range(1,11))

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [42]:
list(np.cumsum(range(1,11)))

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]

In [43]:
list(np.cumsum(range(1,11)))[-1]

55

In [44]:
np.cumsum(range(1,11))[-1]

55

In [48]:
# 누적곱
np.cumprod(range(1,11))

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

### 사용자 정의 함수

In [53]:
# 함수에 입력되는 인수가 몇개인지 모르는 경우 
def sumManyF(*inputValue):
    sum = 0
    for i in inputValue:
        sum += i
    return sum

In [57]:
sumManyF(1,2,3,5,8,4,2,3,1)

29

In [66]:
# 여러개의 숫자를 받아 최대값과 최소값의 차이를 구하는 함수 만들기
def MinMaxF(*inputValue):
    return np.max(inputValue)-np.min(inputValue)


In [67]:
MinMaxF(1,2,3,4,5,6,7,3,2,3,5,7,9,2,10)

9

In [82]:
# 입력되는 값이 Ranage 인 경우 분산과 표준편차를 구하는 함수 만들기
def getEE(inputValue):
    result = f'분산은 : {np.var(inputValue)}, 표준편차는 {np.std(inputValue)}, 평균은 {np.mean(inputValue)}'
    return result

In [83]:
var = [1,2,3,4,5]
getEE(var)

'분산은 : 2.0, 표준편차는 1.4142135623730951, 평균은 3.0'

In [84]:
getEE(range(1,100,2))

'분산은 : 833.0, 표준편차는 28.861739379323623, 평균은 50.0'

In [98]:
# 구구단 함수

def gugudan(x,y):
    for i in x:
        for j in y:
            print(f'{i} x {j} = {i*j}')
        print('---------------')


# def gugu(x,y):
    # print(f'{i*j for i in x for j in y}')


In [99]:
x = [2,5,8]
y = [6,7,8,9]
gugudan(x,y)
#gugu(x,y)

2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
---------------
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
---------------
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
---------------
<generator object gugu.<locals>.<genexpr> at 0x10e6cb430>


In [116]:
def sumF(x,*inputValue):
    if x == 'sum':
        result = np.cumsum(inputValue)[-1]
    elif x == 'mul':
        result = np.cumprod(inputValue)[-1]
    else:
        result = "what are you talking about?"
    return result

In [118]:
print(sumF('sum',1,2,3,4,5))
print(sumF('mul',1,2,3,4,5))

15
120


In [122]:
def sumFF(x,*inputValue):
    #return np.sum(inputValue) if x == 'sum'  np.comprod(inputValue) elif x == 'mul' else 'what are you talking about?'
    #return np.sum(inputValue) elif x == 'sum' : np.comprod(inputValue) if x == 'mul' else 'what are you talking about?'

In [ ]:
sumFF('sum',1,2,3,)

In [124]:
def sum_mul(a,b):
    return a + b , a * b

In [125]:
r_sum, r_mul = sum_mul(2,3)
print(r_sum, r_mul)

5 6


---
### 함수의 Scope

In [126]:
a = 1
def scopeTest1(a):
    return a + 1 

In [127]:
print(scopeTest1(a))
print(a)

2
1


In [129]:
a = 1
def scopeTest1(a):
    a += 1
    return a
print(scopeTest1(a))
print(a)
a = scopeTest1(a)
print(a)

2
1
2


In [131]:
a = 1
def scopeTest1():
    global a    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<,
    a += 1
    return a
    
print(scopeTest1())
print(a)

2
2


### Lambda 함수

In [132]:
addLambda = lambda a, b: a + b

In [133]:
addLambda(10,20)

30