# Library for data analysis by Python

### (1) Pandas      
    - 2008년 금융데이터 분석용으로 출발
    - 통계와 데이터과학, 머신러닝에서 사용

### (2) Numpy 
    - Python 기반 수치해석 Library 
    - 선형대수 연산에 필요한 다차원 배열과 배열 연산을 수행하는 다양한 함수 제공

### (3) Matplotlib
    - Graph or Chart 

### (4) SciPy
    - 과학용 연산에 필요한 다양한 패키지를 모아 놓은 Library
    - 미적분, 선형대수, 행렬연산, 방정식
    - Deep Learning 이후 잘 쓰이진 않음

### (5) scikit-learn
    - Python Library for Machine Learning
    - 회귀분석(Regression), 분류,(Classification), 군집(Clustering)

---
### DataFrame
- Pandas에서 사용하는 기본 데이터
- DataFrame을 정의 할 때는 2차원 리스트를 매개변수로 전달 (Column,Row)


In [1]:
# call Module
import pandas as pd

In [3]:
# List로 DataFrame 만들기
df = pd.DataFrame(
    [
    [10, 20, 30], #Row
    [40, 50 ,60],
    [70, 80, 90]
    ]
)
df

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [6]:
data1 = [10, 20, 30]
data2 = [40, 50 ,60]
data3 = [70, 80, 90]

df = pd.DataFrame(
    [
        data1,
        data2,
        data3
    ]
)
#위에께 이거인거임 
df

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [7]:
data1 = [10, 20, 30, 50]
data2 = [40, 50 ,60]
data3 = [70, 80, 90]

df = pd.DataFrame(
    [
        data1,
        data2,
        data3
    ]
)
df

0   1   2     3
0  10  20  30  50.0
1  40  50  60   NaN
2  70  80  90   NaN

In [26]:
# DataFrame에서 값 추출하기
df.loc[:,0]

# loc를 써야댐 

0    10
1    40
2    70
Name: 0, dtype: int64

In [27]:
# 행(row)기준으로 추출하기
df.loc[0,:]

0    10.0
1    20.0
2    30.0
3    50.0
Name: 0, dtype: float64

In [28]:
# 0번 열과 1번열 불러오기

df.loc[0:1,:]

0   1   2     3
0  10  20  30  50.0
1  40  50  60   NaN

In [29]:
# 0번 열과 1번열 불러오기

df.loc[:,0:1]

0   1
0  10  20
1  40  50
2  70  80

In [32]:
df.loc[:,[0,2]]

0   2
0  10  30
1  40  60
2  70  90

In [33]:
df.loc[:,range(0,2)]

0   1
0  10  20
1  40  50
2  70  80

In [34]:
df.loc[1,1]

50

---
# Series
    - 1 Demension Data

In [35]:
s = pd.Series([1.0,3.0,5.0,7.0,9.0])

In [36]:
s

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

In [40]:
print(s[1:5])

1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64


---
### Dictionary 로 DataFrame 만들기

In [41]:
tbl = pd.DataFrame(
    [
        [80.0, 70.4, 65.5, 45.9, 51.2],
        [170, 180, 155, 143, 154],
        ["f", "n", "n", "t", "t"]
    ]
)
tbl

0     1     2     3     4
0  80.0  70.4  65.5  45.9  51.2
1   170   180   155   143   154
2     f     n     n     t     t

In [43]:
tbl = pd.DataFrame(
    {
       "weight" : [80.0, 70.4, 65.5, 45.9, 51.2],
       "height" : [170, 180, 155, 143, 154],
       "type" : ["f", "n", "n", "t", "t"]
    }
)
tbl

weight  height type
0    80.0     170    f
1    70.4     180    n
2    65.5     155    n
3    45.9     143    t
4    51.2     154    t

In [44]:
type(tbl)

pandas.core.frame.DataFrame

In [46]:
# print weight column

tbl.loc[:,:'weight']

weight
0    80.0
1    70.4
2    65.5
3    45.9
4    51.2

In [60]:
# wight와 height만 출력
tbl.loc[:,['weight','height']]

weight  height
0    80.0     170
1    70.4     180
2    65.5     155
3    45.9     143
4    51.2     154

In [62]:
# 2~3번째 행 출력하기
tbl.loc[2:3,:]

weight  height type
2    65.5     155    n
3    45.9     143    t

In [64]:
# 3번째 이후의 행 출력하기
tbl.loc[3:,:]

weight  height type
3    45.9     143    t
4    51.2     154    t

### 행과 열 기준이 아닌 Data를 비교하여 원하는 값 추출하기

In [66]:
# 키가 160 이상인 Data를 출력하기 

tbl.loc[:,'height'] >= 160


0     True
1     True
2    False
3    False
4    False
Name: height, dtype: bool

In [67]:
tbl.height >= 160

0     True
1     True
2    False
3    False
4    False
Name: height, dtype: bool

In [69]:
tbl[tbl.height >= 160]

weight  height type
0    80.0     170    f
1    70.4     180    n

In [72]:
# type 이 n인 것만 출력하기

tbl[tbl.type == 'n']

weight  height type
1    70.4     180    n
2    65.5     155    n

In [89]:
tbl[(tbl.type == 'n') & (tbl.height >= 150)]
# tbl[tbl.type == 'n' | tbl.type =='t']

weight  height type
1    70.4     180    n
2    65.5     155    n

---
## 정렬의 오름차순과 내림차순

In [91]:
# height 를 기준으로 오름 차순
tbl.sort_values(by='height')

weight  height type
3    45.9     143    t
4    51.2     154    t
2    65.5     155    n
0    80.0     170    f
1    70.4     180    n

In [92]:
tbl.sort_values(by='weight')

weight  height type
3    45.9     143    t
4    51.2     154    t
2    65.5     155    n
1    70.4     180    n
0    80.0     170    f

In [95]:
# height 를 기준으로 내림 차순
tbl.sort_values(by='height', ascending=False)

weight  height type
1    70.4     180    n
0    80.0     170    f
2    65.5     155    n
4    51.2     154    t
3    45.9     143    t

---
### 행과 열의 회전

In [96]:
tbl.T

0     1     2     3     4
weight  80.0  70.4  65.5  45.9  51.2
height   170   180   155   143   154
type       f     n     n     t     t

---
### Numpy를 이용한 데이터 조작

In [98]:
import numpy as np

In [99]:
# 10개의 0으로 된 float32 자료형 데이터 생성
np01 = np.zeros(10, dtype =np.float32)

np01

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [100]:
# 10개의 연소괸 uint64 자료형 데이터 생성
np02 = np.arange(10, dtype=np.uint64)

np02

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint64)

In [102]:
# np02의 값을 3배 증가하기

np02 = np02 * 3
np02

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27], dtype=uint64)

In [104]:
# np02의 평균 구하기

np02.mean()
np.mean(np02) #<< 이쪽으로 

13.5

In [106]:
# np02의 합계 구하기
np02.sum()
np.sum(np02)

135

In [107]:
# 중앙값 구하기

np.median(np02)

13.5

In [109]:
# 분산 구하기
np02.var()
np.var(np02)

74.25

In [112]:
# 표준편차
np02.std()
np.std(np02)

8.616843969807043

In [114]:
# 분산의 제곱근(sqrt) = 표준편차

np.sqrt(np.var(np02)) == np.std(np02)

True

In [119]:
# 표준편차에 제곱을 하면 분산인가 ?
np.var(np02) == np.std(np02) **2

True

In [120]:
np.power(np.std(np02),2)  == np.std(np02) **2

True

In [124]:
# DataFrame 행렬로 변환하기
tbl.values

array([[80.0, 170, 'f'],
       [70.4, 180, 'n'],
       [65.5, 155, 'n'],
       [45.9, 143, 't'],
       [51.2, 154, 't']], dtype=object)

---
### Pandas와 Matplotlib을 이용한 시각화

In [126]:
#!pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 25.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 24.2 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 kB 14.6 MB/s eta 0:00:00a 0:00:01


In [127]:
import matplotlib as plt

In [130]:
names = pd.read_csv("../Data/Baby_Names_1880-2014.csv") # header = 0 (있음), header = 1(없음)
names.head()

name gender  births  year  id
0       Mary      F    7065  1880   1
1       Anna      F    2604  1880   2
2       Emma      F    2003  1880   3
3  Elizabeth      F    1939  1880   4
4     Minnie      F    1746  1880   5

In [131]:
names.tail()

name gender  births  year     id
1825383   Zykeem      M       5  2014  13973
1825384   Zymeer      M       5  2014  13974
1825385  Zymiere      M       5  2014  13975
1825386    Zyran      M       5  2014  13976
1825387    Zyrin      M       5  2014  13977