In [1]:
import numpy as np

In [11]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [9]:
# numpy를 이용하여 1차원 1배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
# 배열의 크기 확인하기
arr1.shape #< 임마는 ()가 없음


(5,)

### 2차원

In [13]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [18]:
# 0으로 거성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# 0으로 구성된 5행 2열의 3차원 배열 생성
np.zeros([3, 5, 2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])