In [1]:
import numpy as np

In [11]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [9]:
# numpy를 이용하여 1차원 1배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
# 배열의 크기 확인하기
arr1.shape #< 임마는 ()가 없음


(5,)

### 2차원

In [13]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [18]:
# 0으로 거성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# 0으로 구성된 5행 2열의 3차원 배열 생성
np.zeros([3, 5, 2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
# 10으로 구성된 배열 생성
np.full(5,10)


array([10, 10, 10, 10, 10])

In [26]:
np.full(7,255)

array([255, 255, 255, 255, 255, 255, 255])

In [28]:
# 0으로 구성된 3행 5열 배열 생성
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [33]:
# 범위가 있는 배열
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [34]:
# 정수형으로 이루어진 배열 -> 실수형으로 변환
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [35]:
arr.dtype

dtype('int64')

In [36]:
type(arr)

numpy.ndarray

In [37]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [38]:
float_arr.dtype

dtype('float64')

### 행열 연산

In [39]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [43]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [45]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [46]:
arr1 * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [50]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
1 / arr1 # 역수

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
(1 / arr1) * arr1  

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5 : 9]

array([5, 6, 7, 8])

In [56]:
arr[5:9] = 12 # 손상된 이미지 복원 할때 사용한다고 하심 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [57]:
arr[:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[7:]

array([12, 12,  9])

### 2차원 배열

In [59]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
# 2번 행의 자료 출력
# arr2d[1:2]
arr2d[1]

array([5, 6, 7, 8])

In [69]:
# 1에서 2번행의 자료 출력
arr2d[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
# 3번 열의 자료 출력
arr2d[:,2]

array([ 3,  7, 11, 15])

In [71]:
# 0,1열의 자료 출력
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [76]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [80]:
# arr[5:9] = 12 # 손상된 이미지 복원 할때 사용한다고 하심 


# np.arange(10)


arr2d = np.arange(1,17)
arr2d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [81]:
arr2d = np.array([
    np.arange(1,5),
    np.arange(5,9),
    np.arange(9,13),
    np.arange(13,17),
])

arr2d[1:[2,3]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
arr2d[:2,1:3] = 0 #<< 차원 축소 (미분)
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 과대적합과 과소적합
    train data를 비워서 예측력을 떨어트리는 ..

### 난수
    Simulation, data없을때

- rand : 0~1 사이의 균일분포
- randn : 가우시안 표준 정규 분포 ()
    가우시안 정규 분포 (Gaussian normal distribution) 라고도 한다. 자연 현상에서 나타나는 숫자를 확률 모형으로 나타낼 때 사용한다. 즉, 수집된 자료의 분포를 근사하는 데에 자주 사용된다.
- randint : 균일 분포의 정수 난수

In [93]:
names = np.array([
    "Charles",
    "Kenny",
    'Hayoung',
    'Charles',
    'Hayoung',
    'Kenny',
    'Kenny'
])

data = np.random.randn(7, 4)

In [95]:
data

array([[ 0.59339816,  0.25295897, -0.07879292, -1.26019086],
       [-0.78523699, -1.02567495, -1.1961129 ,  0.95861502],
       [-1.74570378, -0.58282935, -0.87243409, -1.18957173],
       [-0.77886592,  0.52884164,  0.6312384 ,  0.13578625],
       [-1.7589801 , -0.84428716,  0.4888648 , -0.93976219],
       [-0.99985956, -0.8333987 , -0.76690087,  0.11206351],
       [-1.04417475,  0.17417219, -0.29567226,  0.25237024]])

In [97]:
# Mask
names == 'Charles'

array([ True, False, False,  True, False, False, False])

In [98]:
data[names == 'Charles',:] #True에 해당하는 행 출력

array([[ 0.59339816,  0.25295897, -0.07879292, -1.26019086],
       [-0.77886592,  0.52884164,  0.6312384 ,  0.13578625]])

In [99]:
data[(names == 'Charles') | (names == "Kenny"),:]

array([[ 0.59339816,  0.25295897, -0.07879292, -1.26019086],
       [-0.78523699, -1.02567495, -1.1961129 ,  0.95861502],
       [-0.77886592,  0.52884164,  0.6312384 ,  0.13578625],
       [-0.99985956, -0.8333987 , -0.76690087,  0.11206351],
       [-1.04417475,  0.17417219, -0.29567226,  0.25237024]])

In [100]:
# data의 4번째 열 값중 0보다 적은 것의 mask 만들기

data[:,3] < 0

array([ True, False,  True, False,  True, False, False])

In [101]:
data[data[:,3] <0, :]

array([[ 0.59339816,  0.25295897, -0.07879292, -1.26019086],
       [-1.74570378, -0.58282935, -0.87243409, -1.18957173],
       [-1.7589801 , -0.84428716,  0.4888648 , -0.93976219]])

In [103]:
data[data[:,3] < 0, : ] = 0 # 차원축소
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.78523699, -1.02567495, -1.1961129 ,  0.95861502],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.77886592,  0.52884164,  0.6312384 ,  0.13578625],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.99985956, -0.8333987 , -0.76690087,  0.11206351],
       [-1.04417475,  0.17417219, -0.29567226,  0.25237024]])

In [107]:
arr = np.random.rand(8)
arr

In [111]:
# 오름차순
np.sort(arr) 

array([0.02826179, 0.20217239, 0.24500513, 0.2473112 , 0.32074992,
       0.64679201, 0.69823999, 0.82362746])

In [112]:
# 내림차순
np.sort(arr)[::-1]

array([0.82362746, 0.69823999, 0.64679201, 0.32074992, 0.2473112 ,
       0.24500513, 0.20217239, 0.02826179])

In [113]:
np.sort(arr)[-1] # 마지막거만 나옴 
np.sort(arr)[:-1] # 마지막걸 뺌

array([0.02826179, 0.20217239, 0.24500513, 0.2473112 , 0.32074992,
       0.64679201, 0.69823999])

In [114]:
arr = np.random.rand(5,3)
arr

array([[0.38193269, 0.71712774, 0.05574821],
       [0.72197112, 0.83888977, 0.81770524],
       [0.3136977 , 0.78448114, 0.31102834],
       [0.5913067 , 0.7127229 , 0.23528655],
       [0.57175043, 0.35037673, 0.15110402]])

In [116]:
# 2차원 배열 함수 오름차순
    # 열방향 오름차순
np.sort(arr, axis=0)

array([[0.3136977 , 0.35037673, 0.05574821],
       [0.38193269, 0.7127229 , 0.15110402],
       [0.57175043, 0.71712774, 0.23528655],
       [0.5913067 , 0.78448114, 0.31102834],
       [0.72197112, 0.83888977, 0.81770524]])

In [118]:
    # 열방향 내림차순
np.sort(arr, axis=0)[::-1]

array([[0.72197112, 0.83888977, 0.81770524],
       [0.5913067 , 0.78448114, 0.31102834],
       [0.57175043, 0.71712774, 0.23528655],
       [0.38193269, 0.7127229 , 0.15110402],
       [0.3136977 , 0.35037673, 0.05574821]])

In [119]:
# 행방향 오름차순
np.sort(arr, axis=1)

array([[0.05574821, 0.38193269, 0.71712774],
       [0.72197112, 0.81770524, 0.83888977],
       [0.31102834, 0.3136977 , 0.78448114],
       [0.23528655, 0.5913067 , 0.7127229 ],
       [0.15110402, 0.35037673, 0.57175043]])

In [120]:
# 행방향 내림차순
np.sort(arr, axis=1)[::-1]

array([[0.15110402, 0.35037673, 0.57175043],
       [0.23528655, 0.5913067 , 0.7127229 ],
       [0.31102834, 0.3136977 , 0.78448114],
       [0.72197112, 0.81770524, 0.83888977],
       [0.05574821, 0.38193269, 0.71712774]])

---
### reshape

In [124]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [125]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2, 4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
arr1 = np.reshape(np.arange(1,9),(2,2,2))
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [134]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2)) # (page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [143]:
# 2차원 배열을 1차원 배열로 변경
arr3 = arr1.reshape(-1,1)  # 데이터 몇개인지 정할 수 없을때 -1 로 처리하는거 전에 초기에 한번 말씀하셧던 
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [139]:
#arr3 = arr1.reshape(-1) # 분석할땐 이쪽 , 러닝할때는 위에꺼 
#arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [141]:
arr4 = arr1.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
arr4 == arr3

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [145]:
# 3차원 배열을 1차원으로 변경 

arr5 = arr2.reshape(-1,1)
arr5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [146]:
arr3 == arr5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])